//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAIDE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int TotalTickLimit {
            get {
                return ((int)(this["TotalTickLimit"]));
            }
            set {
                this["TotalTickLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>a</string>
  <string>b</string>
  <string>c</string>
  <string>d</string>
  <string>x</string>
  <string>n</string>
  <string>r0</string>
  <string>r1</string>
  <string>r2</string>
  <string>r3</string>
  <string>r4</string>
  <string>r5</string>
  <string>r6</string>
  <string>r7</string>
  <string>r8</string>
  <string>r9</string>
  <string>r10</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Register32 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Register32"]));
            }
            set {
                this["Register32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Register16 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Register16"]));
            }
            set {
                this["Register16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Register8 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Register8"]));
            }
            set {
                this["Register8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public char CommentChar {
            get {
                return ((char)(this["CommentChar"]));
            }
            set {
                this["CommentChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45, 45, 48")]
        public global::System.Drawing.Color Background {
            get {
                return ((global::System.Drawing.Color)(this["Background"]));
            }
            set {
                this["Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1, 122, 204")]
        public global::System.Drawing.Color WindowFrameActive {
            get {
                return ((global::System.Drawing.Color)(this["WindowFrameActive"]));
            }
            set {
                this["WindowFrameActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66, 66, 66")]
        public global::System.Drawing.Color WindowFrameDisable {
            get {
                return ((global::System.Drawing.Color)(this["WindowFrameDisable"]));
            }
            set {
                this["WindowFrameDisable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("111, 111, 112")]
        public global::System.Drawing.Color FontTitle {
            get {
                return ((global::System.Drawing.Color)(this["FontTitle"]));
            }
            set {
                this["FontTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("241, 241, 241")]
        public global::System.Drawing.Color FontMain {
            get {
                return ((global::System.Drawing.Color)(this["FontMain"]));
            }
            set {
                this["FontMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27, 27, 28")]
        public global::System.Drawing.Color MenuPressed {
            get {
                return ((global::System.Drawing.Color)(this["MenuPressed"]));
            }
            set {
                this["MenuPressed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62, 62, 64")]
        public global::System.Drawing.Color MenuSelected {
            get {
                return ((global::System.Drawing.Color)(this["MenuSelected"]));
            }
            set {
                this["MenuSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51, 51, 55")]
        public global::System.Drawing.Color MenuBorder {
            get {
                return ((global::System.Drawing.Color)(this["MenuBorder"]));
            }
            set {
                this["MenuBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51, 51, 55")]
        public global::System.Drawing.Color MenuSeparator {
            get {
                return ((global::System.Drawing.Color)(this["MenuSeparator"]));
            }
            set {
                this["MenuSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30, 30")]
        public global::System.Drawing.Color TextEditorBackground {
            get {
                return ((global::System.Drawing.Color)(this["TextEditorBackground"]));
            }
            set {
                this["TextEditorBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 150, 150")]
        public global::System.Drawing.Color GroupBorder {
            get {
                return ((global::System.Drawing.Color)(this["GroupBorder"]));
            }
            set {
                this["GroupBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("107, 140, 209, 255")]
        public global::System.Drawing.Color TextEditorSelected {
            get {
                return ((global::System.Drawing.Color)(this["TextEditorSelected"]));
            }
            set {
                this["TextEditorSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51, 51, 51")]
        public global::System.Drawing.Color TextEditorRowId {
            get {
                return ((global::System.Drawing.Color)(this["TextEditorRowId"]));
            }
            set {
                this["TextEditorRowId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15, 15, 15")]
        public global::System.Drawing.Color TextEditorSelectLine {
            get {
                return ((global::System.Drawing.Color)(this["TextEditorSelectLine"]));
            }
            set {
                this["TextEditorSelectLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15, 50, 15")]
        public global::System.Drawing.Color TextEditorRunLine {
            get {
                return ((global::System.Drawing.Color)(this["TextEditorRunLine"]));
            }
            set {
                this["TextEditorRunLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1, 122, 204")]
        public global::System.Drawing.Color DockingTabActive {
            get {
                return ((global::System.Drawing.Color)(this["DockingTabActive"]));
            }
            set {
                this["DockingTabActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45, 45, 48")]
        public global::System.Drawing.Color DockingTabDisable {
            get {
                return ((global::System.Drawing.Color)(this["DockingTabDisable"]));
            }
            set {
                this["DockingTabDisable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45, 45, 48")]
        public global::System.Drawing.Color ButtonNormal {
            get {
                return ((global::System.Drawing.Color)(this["ButtonNormal"]));
            }
            set {
                this["ButtonNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62, 62, 64")]
        public global::System.Drawing.Color ButtonHover {
            get {
                return ((global::System.Drawing.Color)(this["ButtonHover"]));
            }
            set {
                this["ButtonHover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("51, 153, 255")]
        public global::System.Drawing.Color ButtonDown {
            get {
                return ((global::System.Drawing.Color)(this["ButtonDown"]));
            }
            set {
                this["ButtonDown"] = value;
            }
        }
    }
}
