//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAIDE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAIDE.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фон.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные параметры.
        /// </summary>
        public static string BaseSetting {
            get {
                return ResourceManager.GetString("BaseSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 бит.
        /// </summary>
        public static string Bit16 {
            get {
                return ResourceManager.GetString("Bit16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 бита.
        /// </summary>
        public static string Bit32 {
            get {
                return ResourceManager.GetString("Bit32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 бит.
        /// </summary>
        public static string Bit8 {
            get {
                return ResourceManager.GetString("Bit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собрать.
        /// </summary>
        public static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Построение успешно завершено.
        /// </summary>
        public static string BuildDone {
            get {
                return ResourceManager.GetString("BuildDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ходе сборки возникли ошибки.
        /// </summary>
        public static string BuildError {
            get {
                return ResourceManager.GetString("BuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сборка.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажатая кнопка.
        /// </summary>
        public static string ButtonDown {
            get {
                return ResourceManager.GetString("ButtonDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кнопка под курсором.
        /// </summary>
        public static string ButtonHover {
            get {
                return ResourceManager.GetString("ButtonHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартный цвет.
        /// </summary>
        public static string ButtonNormal {
            get {
                return ResourceManager.GetString("ButtonNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кнопки.
        /// </summary>
        public static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешний вид.
        /// </summary>
        public static string ColorSetting {
            get {
                return ResourceManager.GetString("ColorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Символ коментария.
        /// </summary>
        public static string CommentSymbol {
            get {
                return ResourceManager.GetString("CommentSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Консоль не отвечает.
        /// </summary>
        public static string ConsoleDontAnswer {
            get {
                return ResourceManager.GetString("ConsoleDontAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню.
        /// </summary>
        public static string ContextMenu {
            get {
                return ResourceManager.GetString("ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string Contine {
            get {
                return ResourceManager.GetString("Contine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активная вкладка.
        /// </summary>
        public static string DockingTabActive {
            get {
                return ResourceManager.GetString("DockingTabActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не активная вкладка.
        /// </summary>
        public static string DockingTabDisable {
            get {
                return ResourceManager.GetString("DockingTabDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла проблемка.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основной цвет текста.
        /// </summary>
        public static string FontMain {
            get {
                return ResourceManager.GetString("FontMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст заголовка.
        /// </summary>
        public static string FontTitle {
            get {
                return ResourceManager.GetString("FontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рамки групп.
        /// </summary>
        public static string GroupBorder {
            get {
                return ResourceManager.GetString("GroupBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если продолжить работу программы все может полететь в Обливион.
        /// </summary>
        public static string IfContineWarning {
            get {
                return ResourceManager.GetString("IfContineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Память с инструкциями не доступна здесь.
        /// </summary>
        public static string IndexInInstuctionMemory {
            get {
                return ResourceManager.GetString("IndexInInstuctionMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес за пределами выделенной памяти.
        /// </summary>
        public static string IndexMemoryOf {
            get {
                return ResourceManager.GetString("IndexMemoryOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимый параметр {0}.
        /// </summary>
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество операций, сведетельстуеще о зацикливании программы.
        /// </summary>
        public static string loopIterationCount {
            get {
                return ResourceManager.GetString("loopIterationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основное.
        /// </summary>
        public static string MainGroup {
            get {
                return ResourceManager.GetString("MainGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метка &apos;{0}&apos; уже определена.
        /// </summary>
        public static string MarkerFound {
            get {
                return ResourceManager.GetString("MarkerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метка &apos;{0}&apos; не определена.
        /// </summary>
        public static string MarkerNotFound {
            get {
                return ResourceManager.GetString("MarkerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рамка.
        /// </summary>
        public static string MenuBorder {
            get {
                return ResourceManager.GetString("MenuBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытая вкладка.
        /// </summary>
        public static string MenuPressed {
            get {
                return ResourceManager.GetString("MenuPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделение.
        /// </summary>
        public static string MenuSelected {
            get {
                return ResourceManager.GetString("MenuSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разделитель.
        /// </summary>
        public static string MenuSeparator {
            get {
                return ResourceManager.GetString("MenuSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; не является числом.
        /// </summary>
        public static string NotNumber {
            get {
                return ResourceManager.GetString("NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция &apos;{0}&apos; имеет {1} оргумент(а).
        /// </summary>
        public static string OperationsArgumentError {
            get {
                return ResourceManager.GetString("OperationsArgumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция &apos;{0}&apos; не определена.
        /// </summary>
        public static string OperationsNotFound {
            get {
                return ResourceManager.GetString("OperationsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите любую клавишу для продолжения.
        /// </summary>
        public static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможно, Ваша программа зациклилась.\nОстановить ее?.
        /// </summary>
        public static string ProgrammLoop {
            get {
                return ResourceManager.GetString("ProgrammLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком много операций.
        /// </summary>
        public static string ProgrammLoopTitle {
            get {
                return ResourceManager.GetString("ProgrammLoopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезапустить.
        /// </summary>
        public static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистр &apos;{0}&apos; не может использоватся здесь..
        /// </summary>
        public static string RegisterDontUseHere {
            get {
                return ResourceManager.GetString("RegisterDontUseHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистр &apos;{0}&apos; не существует.
        /// </summary>
        public static string RegisterNotFound {
            get {
                return ResourceManager.GetString("RegisterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистр &apos;{0}&apos; не существует или не может использоваться здесь.
        /// </summary>
        public static string RegisterNotFoundOrDontUse {
            get {
                return ResourceManager.GetString("RegisterNotFoundOrDontUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистры.
        /// </summary>
        public static string Registres {
            get {
                return ResourceManager.GetString("Registres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Востановить стандартные настройки.
        /// </summary>
        public static string ResrtToDefault {
            get {
                return ResourceManager.GetString("ResrtToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить.
        /// </summary>
        public static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не обрабатываемая ошибка при выполнении инструкции {0}.
        /// </summary>
        public static string RuntimeException {
            get {
                return ResourceManager.GetString("RuntimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не возможно выполнить инструкцию, эта память не для инструкций.
        /// </summary>
        public static string RuntimeExceptionMemory {
            get {
                return ResourceManager.GetString("RuntimeExceptionMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка {0}: {1}.
        /// </summary>
        public static string RuntimeExceptionRow {
            get {
                return ResourceManager.GetString("RuntimeExceptionRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить все.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения?.
        /// </summary>
        public static string SaveQuery {
            get {
                return ResourceManager.GetString("SaveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстовые радакторы.
        /// </summary>
        public static string TextEditor {
            get {
                return ResourceManager.GetString("TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фон текстового редактора.
        /// </summary>
        public static string TextEditorBackground {
            get {
                return ResourceManager.GetString("TextEditorBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фон панели нумирации.
        /// </summary>
        public static string TextEditorRowId {
            get {
                return ResourceManager.GetString("TextEditorRowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполняемая строка.
        /// </summary>
        public static string TextEditorRunLine {
            get {
                return ResourceManager.GetString("TextEditorRunLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделение.
        /// </summary>
        public static string TextEditorSelected {
            get {
                return ResourceManager.GetString("TextEditorSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая строка.
        /// </summary>
        public static string TextEditorSelectLine {
            get {
                return ResourceManager.GetString("TextEditorSelectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рамка активного окна.
        /// </summary>
        public static string WindowFrameActive {
            get {
                return ResourceManager.GetString("WindowFrameActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рамка не активного окна.
        /// </summary>
        public static string WindowFrameDisable {
            get {
                return ResourceManager.GetString("WindowFrameDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окна.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
    }
}
